### ISSUE TITLE
Add tests to pyaccel

### ISSUE THREAD

**Issue by afonsoharuo** [lnls-fac/code#22]
Tests could be used to define the package API and help development. We could also use tags to identify closed versions.

**Comment by xresende** [comment]
complete tests for:
- pyaccel.elements
- pyaccel.accelerator
- pyaccel.tracking.elementpass

**Comment by LuanaVilela** [comment]
complete tests for:
- pyaccel.lattice

**Comment by xresende** [comment]
moved to new repo
