### ISSUE TITLE
Make function names uniform

### ISSUE THREAD

**Issue by afonsoharuo** [lnls-fac/code#29]
In the optics module, we have getwiss and calctwiss, but get_rffrequency and so on. I suggest we follow a uniform convention. If you agree, which should we choose?

**Comment by xresende** [comment]
*get_rffrequency* just returns a simple attribute of *Accelerator* objects. It should become a property of the object (I think I already implemented it). This function should be deleted from *optics.py*. As for convention, I think we should follow *gettwiss*.

**Comment by xresende** [comment]
done so far.
